# MIT License
#
# Copyright (c) 2026 registerGen
#
# Compile-time error tests for crjson library

set(CRJSON_CT_PARSE_CASES "")
list(APPEND CRJSON_CT_PARSE_CASES [=[empty|R"json()json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[invalid|R"json(invalid)json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[trailing|R"json(42 extra)json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[unterminated_string|R"json("unterminated)json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[escape_end|R"json("hello\)json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[escape_x|R"json("\x")json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[array_no_close|R"json([1, 2, 3)json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[array_no_commas|R"json([1 2 3])json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[array_trailing_comma|R"json([1, 2, 3,])json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[obj_no_close|R"json({"key": "value")json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[obj_no_colon|R"json({"key" "value"})json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[obj_no_comma|R"json({"a": 1 "b": 2})json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[obj_trailing_comma|R"json({"key": "value",})json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[obj_non_string_key|R"json({42: "value"})json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[missing_comma_between_objects|R"json([{"a":1}{"b":2}])json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[missing_array_close|R"json({"a":[1,2})json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[missing_object_close|R"json([{"a":1])json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[deep_missing_close|R"json([[[1, 2])json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[missing_nested_close|R"json({"a": {"b": 1))json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[double_comma_array|R"json([1,, 2])json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[double_comma_object|R"json({"a": 1,, "b": 2})json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[colon_in_array|R"json([1: 2])json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[equals_in_object|R"json({"key" = "value"})json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[single_quote_string|R"json('string')json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[unquoted_key|R"json({key: 'value'})json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[lit_nul|R"json(nul)json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[lit_tru|R"json(tru)json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[lit_fals|R"json(fals)json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[lit_dash|R"json(-)json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[lit_dot|R"json(.)json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[lit_e|R"json(e)json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[unicode_hex_invalid|R"json("\uGGGG")json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[unicode_hex_lower|R"json("\u00g0")json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[unicode_hex_colon|R"json("\u00:0")json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[unicode_hex_tab|"\"\\u\t012\""]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[surrogate_high_only|R"json("\uD83D")json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[surrogate_low_only|R"json("\uDE00")json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[surrogate_followed_by_ascii|R"json("\uD83D\u0041")json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[surrogate_followed_by_escape|R"json("\uD83D\n")json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[surrogate_followed_by_pua|R"json("\uD83D\uE000")json"]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[raw_utf8_ff|"\"\xFF\""]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[raw_utf8_80|"\"\x80\""]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[raw_utf8_c3|"\"\xC3\""]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[raw_utf8_c3_41|"\"\xC3\x41\""]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[raw_utf8_e0|"\"\xE0\x80\xA1\""]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[raw_utf8_c1|"\"\xC1\x81\""]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[raw_utf8_ed|"\"\xED\xA0\x80\""]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[raw_utf8_ed_bf|"\"\xED\xBF\xBF\""]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[raw_utf8_f0|"\"\xF0\x80\x80\x80\""]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[raw_utf8_f4|"\"\xF4\x90\x80\x80\""]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[raw_utf8_f5|"\"\xF5\x80\x80\x80\""]=])
list(APPEND CRJSON_CT_PARSE_CASES [=[control_char|"\"\x01\""]=])

set(CRJSON_CT_BIND_CASES "")
list(APPEND CRJSON_CT_BIND_CASES [=[wrong_root_num|jnum|R"json("string")json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[wrong_root_null|jnull|R"json(42)json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[wrong_root_bool|jbool|R"json(42)json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[wrong_root_arr|jarr<jnum>|R"json(42)json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[wrong_root_obj|jobj<jkv<"x"_fs, jnum>>|R"json(42)json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[array_elem_type|jarr<jnum>|R"json([1, "string", 3])json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[obj_missing_b|jobj<jkv<"a"_fs, jnum>, jkv<"b"_fs, jnum>>|R"json({"a": 1})json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[obj_missing_required|jobj<jkv<"required"_fs, jstr>>|R"json({"wrong": "value"})json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[obj_missing_address|jobj<jkv<"name"_fs, jstr>, jkv<"address"_fs, jobj<jkv<"city"_fs, jstr>>>>|R"json({"name": "Alice"})json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[obj_missing_fields|jobj<jkv<"name"_fs, jstr>, jkv<"age"_fs, jnum>, jkv<"active"_fs, jbool>, jkv<"tags"_fs, jarr<jstr>>, jkv<"metadata"_fs, jobj<jkv<"id"_fs, jnum>>>>|R"json({"name": "Bob", "age": 30})json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[obj_missing_tags|jobj<jkv<"name"_fs, jstr>, jkv<"tags"_fs, jarr<jstr>>>|R"json({"name": "x"})json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[obj_missing_age|jobj<jkv<"name"_fs, jstr>, jkv<"age"_fs, jnum>>|R"json({"name": "x"})json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[obj_extra_required|jobj<jkv<"required"_fs, jstr>>|R"json({"required": "ok", "extra": "x"})json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[obj_extra_point|jobj<jkv<"point"_fs, jtup<jnum, jnum>>>|R"json({"point": [1, 2], "extra": 0})json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[obj_extra_v|jobj<jkv<"v"_fs, jnum>>|R"json({"v": 1, "extra": 2})json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[obj_extra_id|jobj<jkv<"id"_fs, jnum>>|R"json({"id": 1, "extra": 2})json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[obj_extra_city|jobj<jkv<"city"_fs, jstr>>|R"json({"city": "x", "extra": "y"})json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[obj_extra_label|jobj<jkv<"label"_fs, jstr>>|R"json({"label": "x", "extra": "y"})json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[obj_extra_x|jobj<jkv<"x"_fs, jnum>>|R"json({"x": 1, "extra": 2})json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[obj_extra_name|jobj<jkv<"name"_fs, jstr>>|R"json({"name": "x", "extra": "y"})json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[obj_extra_tags|jobj<jkv<"tags"_fs, jarr<jstr>>>|R"json({"tags": [], "extra": 0})json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[obj_extra_rows|jobj<jkv<"rows"_fs, jarr<jtup<jobj<jkv<"name"_fs, jstr>>, jnum>>>>|R"json({"rows": [], "extra": 0})json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[obj_type_mismatch|jobj<jkv<"a"_fs, jnum>, jkv<"b"_fs, jnum>>|R"json({"a": 1, "b": "str"})json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[tup_too_few|jtup<jnum, jnum, jnum>|R"json([1, 2])json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[tup_too_many|jtup<jnum, jnum>|R"json([1, 2, 3])json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[tup_elem_type|jtup<jnum, jstr>|R"json([1, 2])json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[tup_not_array|jtup<jnum>|R"json({"x": 1})json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[tup_single_too_many|jtup<jnum>|R"json([1, 2])json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[tup_num_str_extra|jtup<jnum, jstr>|R"json([1, "x", true])json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[tup_num_str_bool_missing|jtup<jnum, jstr, jbool>|R"json([1, "x"])json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[tup_str_bool_extra|jtup<jstr, jbool>|R"json(["x", true, 1])json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[tup_num_arr_extra|jtup<jnum, jarr<jstr>>|R"json([1, [], 2])json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[tup_arr_bool_extra|jtup<jarr<jnum>, jbool>|R"json([[1, 2], true, 3])json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[tup_obj_num_missing|jtup<jobj<jkv<"name"_fs, jstr>>, jnum>|R"json([{"name": "x"}])json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[tup_str_obj_extra|jtup<jstr, jobj<jkv<"x"_fs, jnum>>>|R"json(["s", {"x": 1}, 0])json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[tup_num_nested_extra|jtup<jnum, jtup<jstr, jbool>>|R"json([1, ["s", true], 0])json"]=])
list(APPEND CRJSON_CT_BIND_CASES [=[tup_obj_label_inner_extra|jtup<jobj<jkv<"label"_fs, jstr>>, jtup<jarr<jnum>, jbool>>|R"json([{"label": "x"}, [[1], true], 0])json"]=])
