#!/usr/bin/env python3
r"""Turn the benchmark CSV into a `plot.tex` snippet.

Reads `<size>,algorithm,time_ms,check` rows and writes a `figure` environment
with a `pgfplots` log-log axis, one `\addplot` per algorithm, the caption below
the plot, and a caption that points at the generated table.

A line plot needs a single numeric, growing axis, so this reads one size column
(`--size-column`, default `n`). If the input size is a pair, keep the varying
dimension in that column and state the fixed one in the caption, or leave the
figure out and let the table carry the result.

Needs `\usepackage{pgfplots}` and `\pgfplotsset{compat=1.18}` in the preamble.
Usage: python3 plot.py [bench.csv] [-o plot.tex]
"""

import argparse
import csv
import os
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))

# CSV algorithm name -> how it is printed in the legend.
LABEL = {
    "naive": r"naive $O(n^2)$",
    "divide-and-conquer": r"divide and conquer $O(n \log n)$",
}

# One entry per curve, in the order they should be drawn.
STYLES = [
    "mark=square*, thick, color=red!70!black",
    "mark=*, thick, color=blue!70!black",
    "mark=triangle*, thick, color=orange!80!black",
    "mark=diamond*, thick, color=teal",
]

LABEL_NAME = "{{NAME}}-bench"
CAPTION = (
    r"Running time of the algorithms (log--log scale); data from "
    r"Table~\ref{tab:" + LABEL_NAME + r"}."
)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("csv_path", nargs="?", default=os.path.join(HERE, "bench.csv"))
    parser.add_argument("-o", "--output", default=os.path.join(HERE, "plot.tex"))
    parser.add_argument("--size-column", default="n",
                        help="the single numeric column used as the x axis")
    args = parser.parse_args()

    series = defaultdict(list)
    order = []
    with open(args.csv_path, newline="") as handle:
        reader = csv.DictReader(handle)
        columns = reader.fieldnames or []
        if args.size_column not in columns:
            raise SystemExit(
                "error: --size-column %r is not a column of %s (columns: %s)"
                % (args.size_column, args.csv_path, ", ".join(columns))
            )
        for row in reader:
            algorithm = row["algorithm"]
            if algorithm not in order:
                order.append(algorithm)
            time_ms = float(row["time_ms"])
            try:
                size = float(row[args.size_column])
            except ValueError:
                raise SystemExit(
                    "error: column %r holds %r, which is not numeric -- a log-log "
                    "line plot needs one growing axis; pass --size-column with the "
                    "varying dimension, or use table.py alone "
                    "(references/report-and-review.md)"
                    % (args.size_column, row[args.size_column])
                )
            if time_ms <= 0:
                print(f"warning: skipping n = {row['n']}, {algorithm}: {time_ms}",
                      file=sys.stderr)
                continue
            series[algorithm].append((size, time_ms))
    if not order:
        raise SystemExit("error: no rows in %s" % args.csv_path)

    plots = []
    for i, algorithm in enumerate(order):
        points = "\n".join(
            f"        ({size:g},{value:.6g})" for size, value in sorted(series[algorithm])
        )
        style = STYLES[i % len(STYLES)]
        plots.append(
            "      \\addplot[%s] coordinates {\n%s\n      };\n" % (style, points)
        )

    legend = ", ".join(LABEL.get(a, a.replace("-", " ").capitalize()) for a in order)
    sizes = sorted({size for points in series.values() for size, _ in points})
    options = [
        "width=0.68\\textwidth",
        "height=0.30\\textwidth",
        "xlabel={input size $n$}",
        "ylabel={running time (ms)}",
        "xmin=%.6g" % (min(sizes) / 2),
        "xmax=%.6g" % (max(sizes) * 2.0),
        "log basis x=10",
        "log basis y=10",
        "grid=major",
        # The legend sits in the corner the curves leave empty.
        "legend pos=south east",
        "legend cell align=left",
        "tick label style={font=\\small}",
        "label style={font=\\small}",
        "legend style={font=\\small, fill=white, fill opacity=0.8, draw opacity=0.5}",
    ]
    tex = "\n".join(
        [
            "% Generated by plot.py -- do not edit by hand.",
            "% Requires \\usepackage{pgfplots} (and \\pgfplotsset{compat=1.18}).",
            "\\begin{figure}[t]",
            "  \\centering",
            "  \\begin{tikzpicture}",
            "    \\begin{loglogaxis}[",
            ",\n".join("      " + option for option in options),
            "    ]",
            "".join(plots).rstrip("\n"),
            "      \\legend{" + legend + "}",
            "    \\end{loglogaxis}",
            "  \\end{tikzpicture}",
            # Figure convention: the caption goes below the plot.
            "  \\caption{" + CAPTION + "}",
            "  \\label{fig:" + LABEL_NAME + "}",
            "\\end{figure}",
            "",
        ]
    )
    with open(args.output, "w") as handle:
        handle.write(tex)
    print(f"wrote {args.output} ({sum(len(v) for v in series.values())} points)")


if __name__ == "__main__":
    main()
