#!/usr/bin/env python3
r"""Turn the benchmark CSV into a `table.tex` snippet.

Reads `<size>,algorithm,time_ms,check` rows (the benchmark driver's output) and
writes a `booktabs` table with `siunitx` `S` columns, times rounded to three
significant figures and a dash where an algorithm did not run.

The size may be several numbers (`n,m,...`); pass them with
`--size-columns n,m` and the table gets one column per dimension.

Needs `\usepackage{booktabs}` and `\usepackage{siunitx}` in the preamble.
Usage: python3 table.py [bench.csv] [-o table.tex]
"""

import argparse
import csv
import math
import os
import re
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))

# CSV algorithm name -> how it is printed in the table.
LABEL = {
    "naive": "Naive",
    "divide-and-conquer": r"Div.\ \& conq.",
}

LABEL_NAME = "{{NAME}}-bench"
CAPTION = (
    r"Average runtime of the algorithms on random inputs, rounded to three "
    r"significant figures. Dashes mark the sizes an algorithm did not run."
)


def num3(x):
    """x rounded to 3 significant figures, as a number `siunitx` can parse."""
    if x == 0:
        return "0"
    exp = math.floor(math.log10(abs(x)))
    mantissa = round(x / 10**exp, 2)
    if abs(mantissa) >= 10:  # rounding pushed it into the next decade
        mantissa /= 10
        exp += 1
    if -3 <= exp <= 2:  # plain decimal, e.g. 0.00274, 82.0, 655
        return f"{x:.{max(0, 2 - exp)}f}"
    return f"{mantissa:g}e{exp}"


def natural_key(size):
    """Sorts `10 < 100 < 1000` and `16x16 < 16x32`, whatever the size looks like."""
    return [int(part) if part.isdigit() else part.lower()
            for part in re.split(r"(\d+)", " ".join(size))]


def widths(numbers):
    """Widest `table-format` needed by `numbers`, e.g. `3.5e1`."""
    total, decimals, exponents = 1, 0, 0
    for number in numbers:
        mantissa, _, exponent = number.partition("e")
        integer, _, fraction = mantissa.partition(".")
        total = max(total, len(integer))
        decimals = max(decimals, len(fraction))
        exponents = max(exponents, len(exponent))
    return f"{total}.{decimals}" + (f"e{exponents}" if exponents else "")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("csv_path", nargs="?", default=os.path.join(HERE, "bench.csv"))
    parser.add_argument("-o", "--output", default=os.path.join(HERE, "table.tex"))
    parser.add_argument("--size-columns", default="n",
                        help="comma separated size columns, e.g. n or n,m")
    args = parser.parse_args()
    size_columns = [c.strip() for c in args.size_columns.split(",") if c.strip()]

    times = defaultdict(dict)
    order = []
    with open(args.csv_path, newline="") as handle:
        for row in csv.DictReader(handle):
            algorithm = row["algorithm"]
            if algorithm not in order:
                order.append(algorithm)
            size = tuple(row[column].strip() for column in size_columns)
            times[algorithm][size] = float(row["time_ms"])
    if not order:
        raise SystemExit("error: no rows in %s" % args.csv_path)

    sizes = sorted({size for series in times.values() for size in series},
                   key=natural_key)
    formatted = {a: {size: num3(t) for size, t in times[a].items()} for a in order}
    time_format = widths([v for a in order for v in formatted[a].values()])

    def cell(algorithm, size):
        if size in formatted[algorithm]:
            return formatted[algorithm][size]
        # `\multicolumn` keeps the dash out of the `S` column's number parsing.
        return r"\multicolumn{1}{c}{---}"

    header = " & ".join(
        [f"${column}$" for column in size_columns]
        + [
            rf"\multicolumn{{1}}{{c}}{{{LABEL.get(a, a.replace('-', ' ').capitalize())} (\unit{{\milli\second}})}}"
            for a in order
        ]
    )
    rows = "\n".join(
        "    " + " & ".join(list(size) + [cell(a, size) for a in order]) + r" \\"
        for size in sizes
    )

    tex = (
        "% Generated by table.py -- do not edit by hand.\n"
        "% Requires \\usepackage{booktabs} and \\usepackage{siunitx} in the preamble.\n"
        "\\begin{table}[t]\n"
        "  \\centering\n"
        "  \\caption{" + CAPTION + "}\n"
        "  \\label{tab:" + LABEL_NAME + "}\n"
        "  \\begin{tabular}{" + "r" * len(size_columns)
        + f" S[table-format={time_format},table-align-exponent=false]" * len(order)
        + "}\n"
        "    \\toprule\n"
        "    " + header + r" \\" + "\n"
        "    \\midrule\n"
        + rows + "\n"
        "    \\bottomrule\n"
        "  \\end{tabular}\n"
        "\\end{table}\n"
    )
    with open(args.output, "w") as handle:
        handle.write(tex)
    print(f"wrote {args.output} ({len(sizes)} sizes x {len(order)} algorithms)")


if __name__ == "__main__":
    main()
